name: event_cascade
description: "A top-down, recent-first Flutter event framework supporting multiple event types, routes, TabControllers, and context-based UI."
version: 0.1.1
homepage: https://github.com/NeuralMobile/event_cascade
repository: https://github.com/NeuralMobile/event_cascade
issue_tracker: https://github.com/NeuralMobile/event_cascade/issues
documentation: https://github.com/NeuralMobile/event_cascade/blob/main/README.md
topics:
  - events
  - navigation
  - state-management

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  melos: ^3.1.1

flutter:
